build:
    environment:
        php: '7.0.6'

tools:
    php_code_sniffer:
        config:
            standard: PSR2

build:
    tests:
        override:
            -
                command: 'phpunit'